### ISSUE TITLE
Support for Polyface Meshes

### ISSUE THREAD

**Issue by jonathan-skymap** [dxfjs/writer#116]
Hi, fantastic library,

I was wondering if the library currently has support for creating polyface meshes?
It should be a variation of the polyline entity, however the section about polyline seems to be empty in the documentation: https://dxf.vercel.app/guide/entities.html#polyline

I found the flag for PolyfaceMesh available and I tried to create it like this:
```
    writer.addPolyline3D(vertices, {
      flags: PolylineFlags.PolyfaceMesh,
      layerName,
    });
```

However, I think I would need to be able to set flags on each vertex, to define faces for example? Am I missing something or is this just not supported yet? If so, do you have any plans to add support for this?

Best regards

**Comment by tarikjabiri** [comment]
Hi

I am planing to implement this in the next version, and it will be a major update to the library.

Currently not supported.

**Comment by jonathan-skymap** [comment]
That's great news! I will be looking forward to the next version 😄 

Sorry for the late reply, I got caught up with other things

**Comment by tarikjabiri** [comment]
Hi, I published an alpha version [@tarikjabiri/dxf](https://www.npmjs.com/package/@tarikjabiri/dxf/v/3.0.0-alpha.1).
It has support for polyface meshes and meshes.

See the [examples](https://github.com/dxfjs/writer/tree/next/examples) folder: `polyline.ts` and `mesh.ts`.

Please repport any issue if found.

Regards.
