### ISSUE TITLE
Fill Rectangle Entity

### ISSUE THREAD

**Issue by Thenmee** [dxfjs/writer#125]
Hello 

I am having an issue filling up entity (Rectangle entity )
how can I implement that considering that I am having an canvas and then I transfer it into .dxf so it can be downloaded  

the downloaded file is full of pixels when  zooming in (of course because the rectangles are not filled )

can you help me doing that? ASAP

Thank you in advance

**Comment by tarikjabiri** [comment]
Hi,

A little background, in the dxf specification there is no entity called rectangle its only a `LWPOLYLINE` entity. And you can't use a fill on entities directly, in cad softwares they attach an entity called `HATCH`, so you should a hatch along side with it specifically a solid hatch.

[HATCH](https://dxf.vercel.app/guide/entities.html#hatch) docs.

Hope this helps you, regards.
