### ISSUE TITLE
Possible to import via CDN?

### ISSUE THREAD

**Issue by Tom1827** [dxfjs/writer#127]
Hi,

I'd really like to use this for a project; any chance to make it importable via a CDN?

Thanks.

**Comment by tarikjabiri** [comment]
Hi,

Of course you can using [jsDelivr](https://www.jsdelivr.com/) it creates urls for es modules and common js. You can use it for any package in npm registry.

regards

**Comment by tarikjabiri** [comment]
Common JS is not supported in the browser only ES Modules.

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script type="module">
    import { DxfWriter } from 'https://cdn.jsdelivr.net/npm/@tarikjabiri/dxf@2.8.9/+esm'

    const dxf = new DxfWriter();
    // your code here
    console.log(dxf.stringify()) // get the dxf content.
    </script>
</body>
</html>
```

<img width="709" alt="dxf" src="https://github.com/dxfjs/writer/assets/6343314/1d981b4e-9ff9-4ed1-8d82-9939b9f63edb">

**Comment by Tom1827** [comment]
Thanks!
