### ISSUE TITLE
addLinearDim is not working precisely (e.g. from Jsketcher)

### ISSUE THREAD

**Issue by NetzerRosenfeld** [dxfjs/writer#145]
Hi,
Not sure if here is the right place, but when drawing in Jsketcher horizontal dimenstion, the dxf value is not precisely.
In the image below you can see it as "8000".
![image](https://github.com/dxfjs/writer/assets/98665653/06ba2c51-cc67-49b0-b89d-2a530836d352)

but the data after using the dxf export is calculate not as horizontal line but as free line with angle.
![image](https://github.com/dxfjs/writer/assets/98665653/41c6de55-1f12-477d-b7f3-59f53bfa6276)

The dxf file:
![image](https://github.com/dxfjs/writer/assets/98665653/ae0246bb-17eb-4c3e-aeb1-b0d6ee0358d9)

And the the wrong calculated of Dimesion with "8066"
![image](https://github.com/dxfjs/writer/assets/98665653/d57bdcc9-33f2-4092-aa4a-cf7cac176442)
Thanks

**Comment by tarikjabiri** [comment]
Hi,

Things seems working for me, I can't reproduce the problem.

<img width="572" alt="jsketcher" src="https://github.com/dxfjs/writer/assets/6343314/f6a92fe5-58a9-4052-8ba2-a0735c59f8d5">
<img width="440" alt="jsketcher-dxf" src="https://github.com/dxfjs/writer/assets/6343314/0f82fcd1-d6f6-459d-b991-2d708bae554c">

Can you please tell what software used to display the dxf output.

Regards

**Comment by NetzerRosenfeld** [comment]
It is local version of Jsketcher after some changes I made.

Now, I download the main version and reproduce it again (https://github.com/xibyte/jsketcher).
![image](https://github.com/dxfjs/writer/assets/98665653/9e2b72b1-0134-4616-bf62-1c3e3ac617b9)

![image](https://github.com/dxfjs/writer/assets/98665653/38058fbf-93d2-40d3-b108-49b51ec4cbcc)
I test the dxf file in this site-https://sharecad.org/

Maybe your version is more updated then the main branch?
