### ISSUE TITLE
trueColor types?

### ISSUE THREAD

**Issue by chris-cooper** [dxfjs/writer#153]
Hi,

I'm a bit confused with the mix of string and number for `trueColor`.  Should it be number throughout?

- https://github.com/dxfjs/writer/blob/next/src/entities/entity.ts#L25
- https://github.com/dxfjs/writer/blob/next/src/tables/layer.ts#L31

**Comment by tarikjabiri** [comment]
Hello, Thank you

You are right it should be `number`.

- https://help.autodesk.com/view/OARX/2023/ENU/?guid=GUID-3F0380A5-1C15-464D-BC66-2C5F094BCFB9

![image](https://github.com/dxfjs/writer/assets/6343314/999ce8c1-5f97-49d3-8315-f769357616d9)

Also the class [TrueColor](https://github.com/dxfjs/writer/blob/next/src/utils/color.ts) still not implemented, I fix this and implement so it can help in assigning the true colors.


Regards.
