### ISSUE TITLE
Stringify Performance

### ISSUE THREAD

**Issue by hschmiedhofer** [dxfjs/writer#25]
Hi, 

for some automation stuff i am working on, i did a quick test-run of your very nice package. 
My intention is to compose a DXF from several sub-drawings, which already works nicely.
These sub-drawings can become quite detailed, though.
My current test-setup parses and inserts entities from an 8MB DXF into an instance of your writer class, which is real quick.

However, for the final write-to-disc, i need to stringify(), which unfortunately takes about 30sec.

Do you think there's a way of speeding things up here?

**Comment by tarikjabiri** [comment]
Hi

I will investigate, 30s is a lot.
I need an example to reproduce.

**Comment by hschmiedhofer** [comment]
> I will investigate, 30s is a lot. I need an example to reproduce.
Thank you so much! I sent you the zipped example project via your email.

**Comment by tarikjabiri** [comment]
Hi,
Now it's about 2s please check ([v2.0.8](https://www.npmjs.com/package/@tarikjabiri/dxf/v/2.0.8)) and close this issue if you are satisfied.
regards

**Comment by hschmiedhofer** [comment]
It's even quicker than that here! Thanks a lot, @tarikjabiri ! :)

**Comment by tarikjabiri** [comment]
@hschmiedhofer very nice 🎉❤
