### ISSUE TITLE
Multiple DIMSTYLE issues

### ISSUE THREAD

**Issue by Colatino** [dxfjs/writer#26]
When I add any number of DimStyles, the generated DXF document won't open on AutoCAD.

Inspecting the file I've found that there is an **AcDbDimStyleTable** subclass before each DIMSTYLE and this is causing the error.

As a workaround I changed the DxfDimStyle and DxfTable classes.

The DxfDimStyle class I commented this line:
```JavaScript
dx.subclassMarker('AcDbDimStyleTable');
```

And on the DxfTable:
``` JavaScript
class DxfTable {
    constructor(name) {
        this.name = name;
        this.maxNumberEntries = 0;
        this.ownerObjectHandle = '0';
        this.handle = Handle.next();
        this.records = [];
    }
    dxify(dx) {
        dx.type('TABLE');
        dx.name(this.name);
        dx.handle(this.handle);
        dx.push(330, this.ownerObjectHandle);
        dx.subclassMarker('AcDbSymbolTable');
        dx.push(70, this.records.length);
        // Added this IF clause to ensure only one AcDbDimStyleTable
        if (this.name == "DIMSTYLE") {
            dx.subclassMarker('AcDbDimStyleTable');
        }
        for (const record of this.records)
            record.dxify(dx);
        dx.type('ENDTAB');
    }
}
```

This change allowed me to open the files on AutoCAD

**Comment by tarikjabiri** [comment]
Hi,
Thank you for the report, you are right and its fixed in [v2.3.5](https://www.npmjs.com/package/@tarikjabiri/dxf/v/2.3.5).
Regards.
