### ISSUE TITLE
The `Text` entity not fully customizable.

### ISSUE THREAD

**Issue by tarikjabiri** [dxfjs/writer#27]
Add support for all properties:
- rotation
- obliqueAngle
- generationFlags
- horizontalAlignment
- verticalAlignment
- secondAlignmentPoint
- relativeXScaleFactor

**Comment by DeepankarGupta13** [comment]
i have also done some work for rotation but not sure how to text it i am not so familiar with ts.
![image](https://user-images.githubusercontent.com/86234577/196392871-26d0c124-c952-42ab-98f2-7ac8c6135ef8.png)

**Comment by tarikjabiri** [comment]
Hi @DeepankarGupta13

- Update to the `v2.5.0`.

Code:
```js
const dxf = new DxfWriter();
dxf.addText(point3d(0, 0), 20, 'Hello World!', {
	rotation: 45,
});
```
Result:

![text-rotation](https://user-images.githubusercontent.com/6343314/196392806-58e54abc-7064-4b8f-8ffd-efb02cbc3072.PNG)

**Comment by DeepankarGupta13** [comment]
Thank you sir.
