### ISSUE TITLE
I am not able to add image in dxf

### ISSUE THREAD

**Issue by DeepankarGupta13** [dxfjs/writer#31]
i tried this

const imgDef = dxf.addImage("door.jpg", 'door.jpg', point3d(20, 20, 0), 10, 10, 1, 0);

the file gets download without any error but the file is not opening it says press enter to continue and after that nothing happens.

i consoled the imgDef i got  this
![image](https://user-images.githubusercontent.com/86234577/196887685-eed342b7-7048-4d30-9ecc-596ed73d5ccd.png)

pls help.

**Comment by tarikjabiri** [comment]
Hi,

Please try this:
```js
// And for the image to show up it should be in same location as the dxf file.
const img = dxf.addImage(".\\door.jpg", 'door.jpg', point3d(20, 20, 0), 10, 10, 1, 0);

// Or use an absolute path so it will show up regardless of dxf location.
const img = dxf.addImage("C:/path/to/image/door.jpg", 'door.jpg', point3d(20, 20, 0), 10, 10, 1, 0);
```

You can take a look in the example code in [docs](https://dxf.vercel.app/guide/entities.html#image)

regards

**Comment by DeepankarGupta13** [comment]
sir, it's still not working same issue as above press enter to continue tried absolute path, move the file inside the src folder.

**Comment by tarikjabiri** [comment]
Can I ask how you visualize your dxf file

**Comment by DeepankarGupta13** [comment]
![image](https://user-images.githubusercontent.com/86234577/196899578-f3015f28-2f2f-4000-a5cf-7552c75ed861.png)
like this

**Comment by tarikjabiri** [comment]
Ok you are using AutoCAD.
I can't reproduce can I have a look at your code if possible or an example producing the same result so I can investegate

**Comment by DeepankarGupta13** [comment]
[](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2021/ENU/AutoCAD-Core/files/GUID-18152523-0866-40EF-BC6D-8FAA1127BDD9-htm.html)

this are the steps to add image in autocad dxf

**Comment by DeepankarGupta13** [comment]
https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2021/ENU/AutoCAD-Core/files/GUID-18152523-0866-40EF-BC6D-8FAA1127BDD9-htm.html

**Comment by DeepankarGupta13** [comment]
these are the steps to attach image in autocad dxf

**Comment by tarikjabiri** [comment]
Note that I am also a AutoCAD user so I now how to use it.
I jsut asked to know which softawre you are using.
Autocad is the most good software at reading dxf files.

I asked about your code using my lib so I can investegate why you got that error

**Comment by DeepankarGupta13** [comment]
i am using vuejs

**Comment by tarikjabiri** [comment]
Did you push the changes I cant see where you are using `addImage()`

**Comment by DeepankarGupta13** [comment]
srry i shared wrong link i changed now 
this is the new link
https://github.com/DeepankarGupta13/ThreeJS_Test/blob/dxfWriter/src/script.js

**Comment by DeepankarGupta13** [comment]
i got it now in the dxf file 

0
SECTION
2
HEADER
9
$ACADVER
1
AC1021
9
$LASTSAVEDBY
1
@tarikjabiri/dxf
9
$HANDSEED
5
1E
9
$INSUNITS
70
0
9
$CLAYER
8
0
9
$VIEWCTR
10
462419.04
20
576568.45
0
ENDSEC
0
SECTION
2
CLASSES
0
ENDSEC
0
SECTION
2
TABLES
0
TABLE
2
VPORT
5
1
330
0
100
AcDbSymbolTable
70
1
0
VPORT
5
19
330
1
100
AcDbSymbolTableRecord
100
AcDbViewportTableRecord
2
*Active
70
0
10
0
20
0
11
1
21
1
12
462419.04
22
576568.45
13
0
23
0
14
10
24
10
15
10
25
10
16
0
26
0
36
1
17
0
27
0
37
0
40
3.4409301069099456
41
2
42
50
43
0
44
0
50
0
51
0
71
0
72
100
73
1
74
3
75
0
76
1
77
0
78
0
281
0
65
1
110
0
120
0
130
0
111
1
121
0
131
0
112
0
122
1
132
0
79
0
146
0
348
10020
60
7
61
5
292
1
282
1
141
0
142
0
63
250
421
3358443
0
ENDTAB
0
TABLE
2
LTYPE
5
2
330
0
100
AcDbSymbolTable
70
3
0
LTYPE
5
12
330
2
100
AcDbSymbolTableRecord
100
AcDbLinetypeTableRecord
2
ByBlock
70
0
3

72
65
73
0
40
0
0
LTYPE
5
13
330
2
100
AcDbSymbolTableRecord
100
AcDbLinetypeTableRecord
2
ByLayer
70
0
3

72
65
73
0
40
0
0
LTYPE
5
14
330
2
100
AcDbSymbolTableRecord
100
AcDbLinetypeTableRecord
2
Continuous
70
0
3
Solid line
72
65
73
0
40
0
0
ENDTAB
0
TABLE
2
LAYER
5
3
330
0
100
AcDbSymbolTable
70
1
0
LAYER
5
15
330
3
100
AcDbSymbolTableRecord
100
AcDbLayerTableRecord
2
0
70
0
62
7
6
Continuous
370
0
390
0
0
ENDTAB
0
TABLE
2
STYLE
5
4
330
0
100
AcDbSymbolTable
70
1
0
STYLE
5
16
330
4
100
AcDbSymbolTableRecord
100
AcDbTextStyleTableRecord
2
Standard
70
0
40
0
41
1
50
0
71
0
42
1
3
txt
4

0
ENDTAB
0
TABLE
2
VIEW
5
5
330
0
100
AcDbSymbolTable
70
0
0
ENDTAB
0
TABLE
2
UCS
5
6
330
0
100
AcDbSymbolTable
70
0
0
ENDTAB
0
TABLE
2
APPID
5
7
330
0
100
AcDbSymbolTable
70
1
0
APPID
5
17
330
7
100
AcDbSymbolTableRecord
100
AcDbRegAppTableRecord
2
ACAD
70
0
0
ENDTAB
0
TABLE
2
DIMSTYLE
5
8
330
0
100
AcDbSymbolTable
70
1
100
AcDbDimStyleTable
0
DIMSTYLE
105
18
330
8
100
AcDbSymbolTableRecord
100
AcDbDimStyleTableRecord
2
Standard
70
0
340
16
0
ENDTAB
0
TABLE
2
BLOCK_RECORD
5
9
330
0
100
AcDbSymbolTable
70
2
0
BLOCK_RECORD
5
C
330
9
100
AcDbSymbolTableRecord
100
AcDbBlockTableRecord
2
*Model_Space
70
0
280
1
281
0
0
BLOCK_RECORD
5
F
330
9
100
AcDbSymbolTableRecord
100
AcDbBlockTableRecord
2
*Paper_Space
70
0
280
1
281
0
0
ENDTAB
0
ENDSEC
0
SECTION
2
BLOCKS
0
BLOCK
5
D
330
C
100
AcDbEntity
8
0
100
AcDbBlockBegin
2
*Model_Space
70
0
10
0
20
0
30
0
3
*Model_Space
1

0
ENDBLK
5
E
100
AcDbEntity
8
0
100
AcDbBlockEnd
0
BLOCK
5
10
330
F
100
AcDbEntity
8
0
100
AcDbBlockBegin
2
*Paper_Space
70
0
10
0
20
0
30
0
3
*Paper_Space
1

0
ENDBLK
5
11
100
AcDbEntity
8
0
100
AcDbBlockEnd
0
ENDSEC
0
SECTION
2
ENTITIES
0
IMAGE
5
1B
330
D
100
AcDbEntity
8
0
100
AcDbRasterImage
90
0
10
462419.04
20
576568.45
30
0
11
0.0005580357142857143
21
0
31
0
12
0
22
0.0005580357142857143
32
0
13
1792
23
1280
340
1A
70
3
280
1
281
50
282
50
283
0
360
1C
71
1
91
2
14
-0.5
24
-0.5
14
1791.5
24
1279.5
290
1
0
ENDSEC
0
SECTION
2
OBJECTS
0
DICTIONARY
5
A
330
0
100
AcDbDictionary
281
1
3
ACAD_GROUP
350
B
3
ACAD_IMAGE_DICT
350
1D
0
DICTIONARY
5
B
330
A
100
AcDbDictionary
281
0
0
IMAGEDEF
5
1A
330
1D
102
{ACAD_REACTORS
330
1D
330
1C
102
}
100
AcDbRasterImageDef
1
C:/Users/deepa/OneDrive/Desktop/threejsPrac/ThreeJS_Test/src/test.png
10
1792
20
1280
11
1
21
1
280
1
281
0
0
IMAGEDEF_REACTOR
5
1C
330
0
100
AcDbRasterImageDefReactor
90
2
330
1B
0
DICTIONARY
5
1D
330
A
100
AcDbDictionary
281
0
3
test
350
1A
0
ENDSEC
0
EOF

this was getiing copied i removed and it worked.

**Comment by DeepankarGupta13** [comment]
IMAGEDEF
5
1A
330
1D
102
{ACAD_REACTORS
330
1D
330
1C
102
}
100
AcDbRasterImageDef
1
C:/Users/deepa/OneDrive/Desktop/threejsPrac/ThreeJS_Test/src/test.png
10
1792
20
1280
11
1
21
1
280
1
281
0
0
IMAGEDEF_REACTOR
5
1C
330
0
100
AcDbRasterImageDefReactor
90
2
330
1B
0

this code was getting repeated in the dxf file i removed and it worked.

**Comment by tarikjabiri** [comment]
And why is repeated like that is it my lib doing that 🤔

**Comment by DeepankarGupta13** [comment]
i guess so, because i am calling the addImage() function only once.

**Comment by tarikjabiri** [comment]
I found the issue, these [lines](https://github.com/dxfjs/writer/blob/main/src/Sections/EntitiesSection/EntitiesManager.ts#L190-L191) shouldn't be there 🤦‍♂️.

Also I am using AutoCAD 2013 is not complaining about this it opens the dxf with no errors.

I was adding those object twice so they getting serialized twice.

**Comment by DeepankarGupta13** [comment]
thanks sir.
