### ISSUE TITLE
not able to justify the text to middle center

### ISSUE THREAD

**Issue by DeepankarGupta13** [dxfjs/writer#34]
when I am doing this
function drawText() {
    const text = dxf.addText(point3d(20, 20, 0), 1, 'GGWP', {
        rotation: 30,
        horizontalAlignment: 1,
        verticalAlignment: 2,
    })
    console.log('text: ', text);
}
the position of the text becomes origin
![image](https://user-images.githubusercontent.com/86234577/198516752-382f6ec8-8a43-4c23-aab9-7141b320f567.png)
I tried second alignment point also 
text.secondAlignmentPoint = point3d(20, 20, 0);
it is also not working
pls help

**Comment by tarikjabiri** [comment]
Hi,

I think it's the expected behavior 🤔.

**Comment by DeepankarGupta13** [comment]
Sir, if i want to add my text at (20,20) and the text justify should be middle center. How i should i do that?

**Comment by tarikjabiri** [comment]
Ohhhh the text is moved to the 0,0 when using alignement.

This is a bug I will fix it.

**Comment by tarikjabiri** [comment]
Update to `v2.5.3` and try this:
```js
import { DxfWriter, point3d, TextHorizontalAlignment, TextVerticalAlignment } from "@tarikjabiri/dxf";
const dxf = new DxfWriter();
dxf.addText(point3d(20, 20), 1, 'GGWP', {
	rotation: 30,
	horizontalAlignment: TextHorizontalAlignment.Center,
	verticalAlignment: TextVerticalAlignment.Middle,
	secondAlignmentPoint: point3d(20, 20),
});
```

**Comment by DeepankarGupta13** [comment]
thank you sir.
