### ISSUE TITLE
Hatching pattern ANSI31 is not showing correctly

### ISSUE THREAD

**Issue by DeepankarGupta13** [dxfjs/writer#43]
hi sir,
Currently ANSI31 shows the below pattern
![image](https://user-images.githubusercontent.com/86234577/203031130-5d873aea-8773-4913-a17d-1e1045e71b95.png)

and the pattern which is shown in autocad is
![image](https://user-images.githubusercontent.com/86234577/203031683-b68aec25-9781-4988-bdd6-920b5524c972.png)

**Comment by divya-shiv-pandey** [comment]
I had also been facing similar issue with ANSI31 and Solids. Although the property shows to be ANSI31 but is not. Was in doubt I had messed up exportation process. Any solutions for this one?
![image](https://user-images.githubusercontent.com/64896932/203035983-ae254711-0407-4095-a06b-839501b9bf6e.png)
